language: node_js
node_js:
  - '10'
install:
  - npm install
  - npm install --prefix ./front-end
deploy:
  provider: heroku
  api_key:
    secure: NMcbAa2Tn77rOSyUH1682qaezlWFMDhD3fR43xXGW6P+jrEFpkjRXuJDW/mFQ+YzdhgVueLbZCFxYfr2STaNLG5T0/pBqHtGyIr6lu7eOQpVwZ4uUqyHbaf6L29sNcVp70jpRY11yyp03IqjV+19WDchBH1rSkZaC0MOq8DZqCILctUUCFj6n8BHIYFJENy8KPaYzlvScm11ZiJskadGr68m6zbs1GSPTPQQATkZ88Ouj5o9NA2ukjtGG+thDtsqU4kBQ8y4P1N9tV+drP++gfGKz4zcDPvDynEI00Fpf1G9EXYX8ms0aaNiVovtsV1NC79NRXggsAIKkWlJj7NIJzs0tUldK5so3tfv2REMeNtXOr2Svnns6YwASAuhU4juV2z6dfAPifpfB0eXZQMWSHOoPUDZPNfARE7nyjIuGpT5GppdZRofIx6UV7BPDBdqZSjwln4xUtSgEznxrfjSiVNyFy5Be2XQfuKZf4D+PEL5YBJOb3b5rhuub0K3cmnPlzT6GniCiXbdrU6r4w7omc2Sox7KJ2FFv1Bd3UP6UI6ckktgX/Hvy7q7clQl3MGRhEGSCb+PCyTgFYPCsOtER92slmgr7NBYnUW/k4ZD1Kl8Gd7Rvy6BgbbDWsrXRwmXbjuEQb/ebcqQi9Z0RP8SvnlmXPRvuPweakNR0BdOb0E=
  skip_cleanup: true
  app: cyclopt-js-starter-kit
  on:
    repo: cyclopt/js-starter-kit
